### ISSUE TITLE
#needs/#needstype consistency

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#437] opened 2016-03-04 03:42 UTC
I'm having trouble getting these to work on Foulspawn. I've had problems with them in the past (tellingly, with clockworks), and I'm not entirely sure this is unrelated, for that matter.

Anyway. Currently #generateitem 1 rarm gives a rarm slot which either #needs or #needstype an rweapon slot as per each given sort of arm or arms. I previously did this with weapon slots, but it didn't seem to be helping, and I thought it might be the unit variance code, but now having offloaded it to rweapon I'm not sure, as the misbehavior appears identical. I did a walkthrough in debug mode, and it appears that when #generateitem is processed, the #needs for the slot are never considered. E.g., the rarm "crab" sets a #needs rweapon pincer, but the rweapon is randomly set to greatclub by getSuitableItem. The same sorts of outcomes were happening when it was trying to set the weapon slot instead of rweapon, though, so I'm not sure it's just a matter of generateitem. 

If you get a chance to look at this, it'd be appreciated. I know my pose structures are convoluted messes right now, so it's possible I'm just fundamentally misunderstanding how something should/can be structured. Barring that, though, generating a test nation should show the sorts of problems fairly quickly; e.g. tentacles/pincers that aren't supposed to have artificial weapons with any such weapons, single right arms holding halberds that are only supposed to be used for "two right arms" arms, etc.

**Comment by elmokki** [comment] 2016-03-04 10:00
This was simpler than it seemed. `#needs `is processed when item is added so it may be overwritten later. `#generateitem` is one of the first things to be processed (it wasn't but it had to be changed due to caelian wings containing stat changes) so it isn't the best spot for #needs. If there is a legitimate need for late-in-generation `#generateitem` I can add a separate version to unit.polish().

Now, the issue you have here is that you have `#generateitem 1 rarm` before `#generateitem 1 rweapon`. I'm not entirely sure if the rweapon one is needed, but what it does in this order is:

1. Generate rarm
2. Use rarm needs to generate a rweapon if they exist
3. Generate a rweapon

When switching them around it is:

1. Generate rweapon
2. Generate a rarm
3. Use rarm needs to generate a rweapon if they exist

You probably just want to remove rweapon generation unless I understood wrongly though.

You also seem to have `#generateitem 1 head` lines which is redundant.

**Comment by elmokki** [comment] 2016-03-04 10:09
Also, you could probably move rweapon to weapon by adding `#chanceinc slottag not rarm can_have_1h *0` to one handed weapons and that tag to arms that can have onehanders. `#chanceinc slottype` could be added too. The foul spawn work beautifully right now though so no real need to change it, it's just how I would've done it unless I had just split it to a dozen poses or simply had rarm+rweapon combinations be weapons.

**Comment by Ealb** [comment] 2016-03-05 04:20
So if I understand the above correctly, it should work if I remove rweapon and move everything back to being set in rarm to #need/#needstype various weapons? Unfortunately, that doesn't seem to help - it was what drove me to add in the unnecessary rweapon slot. I'll upload my current setup like that; as an example of stuff still going wrong, here's Wunom -116848301:

![preview_100_wunom](https://cloud.githubusercontent.com/assets/12613576/13545570/a1475ca6-e25e-11e5-9bcd-2a0db2843def.png)

All the units with tentacles are supposed to only have various sorts of tentacles (though I'll admit at this point I'm on the verge of making a grasping tentacle graphic and let them have weapons, or more likely make a wrapped-around tentacle variant arm that *can* have weapons), and all the turtle-shelled units (i.e., the ones with crab heads) shouldn't have armor (but I suspect that latter is an engine limitation, and I should probably either make turtleshells into a (natural) armor instead of a basesprite, or I should make an unarmored pose and only have shells there). rarm is setting "#needstype weapon tentacle", and basesprite is setting "#needs armor none"; in both cases, the unit is still getting non-matching weapons/armors assigned, both in terms of equipped weapons and types of tentacle effects that were meant to be associated with the smaller, weaker multiple tentacles rather than the single large tentacles the units have.

**Comment by Ealb** [comment] 2016-03-05 04:31
Note the above seed is generated from the version in the repository right now; i.e., the one with foulspawn race basechance at 10000.

**Comment by Ealb** [comment] 2016-03-05 07:41
Also note that my fork (as opposed to the master version) probably wouldn't break the above seed, but it might; after having frustrated myself with this issue for the last several days, I went ahead and spent a couple of hours adding mounts to Atlantians in order to vent a bit.

**Comment by elmokki** [comment] 2016-03-05 10:45
My main point was that the version I looked at seemed to work with just swapping `#generateitem 1 rarm` to be after `#generateitem 1 rweapon`.

> So if I understand the above correctly, it should work if I remove rweapon and move everything back to being set in rarm to #need/#needstype various weapons?

No. What I meant is it (probably) works if you remove rweapon, add stuff like `#chanceinc slottag rarm can_have_onehanders` and tag suitable  rarm items with `#can_have_onehanders`. No need for `#needs` or `#needstype`.

Anyway, the issues you are running to are:
1. `#generateitem` is done at the start of generation
2. `#needs` and `#needstype` are done when items are added for an unit

Simply put, the current setup works in this order:
1. Generates a basesprite and and then `#needs` the "none" armor when it is that turtle shell
2. Generates rarm from `#generateitem` and then `#needstypes` a weapon for it
3. Replaces the armor in troop generation since there are zero restrictions in armor files for what can be generated.
4. Replaces the weapon in troop generation since there are zero restrictions in weapon files for what can be generated.

The previous version did the same for armor, but replaced the weapon (rweapon) already in `#generateitem` part.

You can get around everything with separate poses. The way I recommend doing it is, however, just doing it all with `#chanceinc slottag [not] <slot> <tag>`. 

Basically add every non-none armor `#chanceinc slottag basesprite this_basesprite_cannot_have_armor *0` and tag the turtle basesprite with `#this_basesprite_cannot_have_armor`. Or use whatever tags. 

As for weapons, I already wrote it, but you'd either add to all onehanders for example
`#chanceinc slottag not basesprite onehanded_arm *0` or set basechances 0 everywhere and add `#chanceinc slottag basesprite onehanded_arm <basechance>`. Then, of course, add `#onehanded_arm` to the rarms that can have onehanders. Repeat this.

Simply put, I think you are assuming that `#needs` and `#needstype` are handled last instead of as soon as possible.

**Comment by elmokki** [comment] 2016-03-05 10:50
I guess I could also just code stuff like `#addthemeinc '<write themeinc here>'` to items so you could add `#themeinc thisitemtag not no_armor *0` to the turtle basesprite or similar stuff for rarms.

**Comment by elmokki** [comment] 2016-03-05 12:26
#441 adds both `#addthemeinc` and an ability to truly force slots by handling the `#needs` type commands `#forceslot` and `#forceslottype` at unit polishing state. Forcing weapons, armor and offhand slots however can cause some pretty adverse effects when the game thinks the unit will have a twohander and full plate but it will actually have something completely different, so please use `#addthemeinc` instead.

For an example use of `#addthemeinc` look at the turtle basesprite and none armor.

**Comment by elmokki** [comment] 2016-03-05 13:22
I might consider tweaking #forceslot to actually just be generated early and to lock any slot modifications. That would be a bit more error prone if used badly, but wouldn't skew the generation on important slots.

Doesn't really matter though since the way troopgenerator works I highly recommend letting it handle armor and weapon generation while you use chanceincs and themeincs to control what it can choose from.

**Comment by elmokki** [comment] 2016-03-05 13:30
As one last note before I probably won't look at this today: The way you are attempting to do these is great. I would've done something completely different that would've made way more clutter, but now I would do it with `#addthemeinc` like in the example I committed earlier.

**Comment by Ealb** [comment] 2016-03-05 18:28
Hehe. I am totally unsurprised that my problem is that NG is not running like the pristine, elegant structure my formal comp sci/linguistics background so desperately craves. It's also probably not helped that I've been working on this stuff at times when I should be asleep. I had a realization last night that I'm wandering dangerously close to thinking of unit generation in terms of lovely, abstract little finite state machines, eek.

I should be able to spend a decent chunk of time today looking at this - during "normal waking hours", even! - so hopefully my work product will be a bit more meticulous than it has been...

**Comment by elmokki** [comment] 2016-03-05 22:25
In a sense it is working quite well for what `#needs` was designed for: Making one item assign multiple slots like for the Agarthan ranged ammo pouches. It's just that the command is named quite unclearly. If I were writing it all from scratch it'd probably be `#setslot` or something

**Comment by Ealb** [comment] 2016-03-06 14:41
That last comment was like you flipped a switch in my head, and I ended up re-writing the weapon/arm relationship again (the body/armor stuff still uses the new code, though). Current data structures are significantly more NationGeny, in that a weapon is selected first, which then invokes #needstype for an arm to match it. It's working very well (though I still need to figure out a messy web of basechances), except for one minor nagging problem - I can't remember what I need to to do to ensure that an offhand shield or weapon generates even though there's a two-handed weapon in the main hand (well, in this case and very much to the point, hands).

**Comment by elmokki** [comment] 2016-03-06 17:07
On main hand weapons `#ignore_dw_restrictions` makes unit with that main hand weapon able to have shield/offhand weapon regardless of the weapon. I will commit a version where this should work on pose/race/any item the unit has as well.

On filters/pose/race/after next commit any item as well `#dw_maxlength` allows setting maximum length of main hand weapon for DW (default 2), but twohanders will still be ignored.

**Comment by Ealb** [comment] 2016-03-06 18:44
I'm fairly pleased with how things are looking.

![preview_102_agovo](https://cloud.githubusercontent.com/assets/12613576/13556186/5da855ce-e3a1-11e5-96db-8ddef49205b2.png)

All that should remain here is helmets and hands, and I can move onto the next pose-set...

**Comment by elmokki** [comment] 2016-03-06 18:47
It looks gorgeous. 

Helmets may need a (tiny) bit of extra coding if you want natural armor to result in heavier helmets. Currently helmet is determined largely by the prot of armor. Then again if a turtle shell gives natural prot 20, that applies to head as well so I don't know.

**Comment by Ealb** [comment] 2016-03-06 20:38
I'm pretty okay with "I've got a hard head, who needs a helmet?" hubris. If it seems like it's cropping up too much on another frame (most like candidate: beast "cavalry"), I may reconsider though.

**Comment by elmokki** [comment] 2016-03-06 20:47
Just by the way, I firmly believe foul spawn should have both beast "cavalry" and beast cavalry.

Anyway, as for the category poses, do you think it's fine if we just manually select a foul spawn, greyscale it, darken it to almost black and add a yellow question mark on top of it? An another alternative would be the same but also design some sort of tiny icons for ranged/infantry/cavalry so you can actually distinguish infantry and ranged without mouseovering

**Comment by Ealb** [comment] 2016-03-07 00:31
That seems reasonable - I think I was gonna suggest something like the greyscale, actually. It would be ideal if they could be discerned at a glance though, yeah.

Heh - I'd not considered the possibility of "beast" cavalry - only beast "cavalry" (like the vanilla spider-centaur thing) and beast cavalry (like, well, the pretty much everything in NG). That really is a good point though - if your rider can be a mess of tentacles and spines, is it fair for their horse (or "horse") to settle for a mere four uniform limbs? Hehehe...

I only did one play-test of montag_men - can template units be chosen as PD? In my test, PD was all the second race. I would really, really love it if PD could consist of template units so you end up with an ever-changing mess of a province garrison every time there's a battle in your territory.

**Comment by elmokki** [comment] 2016-03-07 08:29
Oh yeah, PD generation will probably need a slight rework to get template units chosen. They can be chosen since they could be chosen for start army, but they should have some prioritization.

**Comment by Ealb** [comment] 2016-03-07 13:29
When you're messing with PD gen, if it wouldn't be too much trouble it would be nice to have a "PD only" pose option added so a nation could have e.g. skellies like Nazca (or - heh - mechanical men or vine men or such) for their PD.

Ha, it would be really entertaining if you could rarely end up with a very low ratio of a non-cap-only national monster as second-tier PD...

**Comment by elmokki** [comment] 2016-03-07 15:17
That pretty much needs a rewrite. A rewrite it deserves though.

**Closed** 2016-03-22 02:07 UTC
Labels: bug, functionality
