### ISSUE TITLE
FSA: Bad Image File

### ISSUE THREAD

**Issue by McGoatDaElite** [elmokki/nationgen#1201] opened 2024-10-12 03:12 UTC
![Nationgen Error 1](https://github.com/user-attachments/assets/2abd71a3-ed55-4126-b486-e4c96a5644f9)

![Nationgen Error 2](https://github.com/user-attachments/assets/1eb69ea5-e9e5-4c76-b4ab-db340a108261)

-- NationGen - nationgen_library_of_divinity
-----------------------------------
-- Generated with version 0.9.0.
-- Generation setting code: 0
-- Nation seeds generated with seed 6423154012952421843.
-- Nation 150: Pythinth generated with seed -2376672812677083508
-- Nation 151: Moto generated with seed -5072395704801933740
-- Nation 152: Malopolis generated with seed -6019781878465422854
-- Nation 153: Hessea generated with seed 7874708065924948639
-- Nation 154: Reggwald generated with seed -8421710143804036888
-- Nation 155: Hedsand generated with seed 6937598933884356081
-- Nation 156: Abyseos generated with seed -5044540448611833352
-- Nation 157: Tanau generated with seed 2095480714716770125
-- Nation 158: Yoriro generated with seed 5317900597090477179
-- Nation 159: Binkos generated with seed 931152773448808158
-----------------------------------

[Nationgen Error banner.xcf.gz](https://github.com/user-attachments/files/17348632/Nationgen.Error.banner.xcf.gz)

Another notable piece of information, with Dominions 6 specifically I had to insert the nationgen .dm file inside of the nationgen folder generated alongside it for it to appear in the games mod list. I do not know if this would have an effect or not but I did have to do that to even get this far, which was not necessary on Dominions 5.

**Comment by elmokki** [comment] 2024-10-12 09:00
The reason for the error is the file path: It has nationgen_library_of_divinity folder twice in a row for some weird reason.

**Comment by elmokki** [comment] 2024-10-12 09:10
Yes, I confirmed. At least on Windows 10 mods are only visible if I move the .dm inside the folder, and if I do that, the file references break. 

If this is consistent over operating systems, it's a simple fix. If it isn't, there need to be some UI changes to make it toggleable.

**Comment by elmokki** [comment] 2024-10-12 14:41
Right, this should be fixed in the next released version, whenever that is. # #

**Closed by elmokki** 2024-10-12 14:41 UTC
